#ifndef _HAL_ERR_
#define _HAL_ERR_

#define HAL_SUCCESS 0L
#define HAL_ERR_FAILURE 1L
#define HAL_ERR_DEVICE_NOT_FOUND 2L
#define HAL_ERR_DEVICE_BLOCK_NOT_FOUND 3L
#define HAL_ERR_POINTER_NULL 4L
#define HAL_ERR_DEVICE_IS_STARTED 5L
#define HAL_ERR_DEVICE_IS_STOPPED 6L
#define HAL_ERR_FIFO_ERROR 7L
#define HAL_ERR_RESET_ERROR 8L
#define HAL_ERR_MEM_ERROR 9L
#define HAL_ERR_NOT_POLLED 10L
#define HAL_ERR_FIFO_NO_ROOM 11L
#define HAL_ERR_BUFFER_TOO_SMALL 12L
#define HAL_ERR_NO_DATA 13L
#define HAL_ERR_REGISTER_ERROR 14L
#define HAL_ERR_INVALID_PARAM 15L
#define HAL_ERR_NOT_SGDMA 16L
#define HAL_ERR_LOOPBACK_ERROR 17L
#define HAL_ERR_NO_CALLBACK 18L
#define HAL_ERR_NO_FEATURE 19L
#define HAL_ERR_NOT_INTERRUPT 20L
#define HAL_ERR_DEVICE_BUSY 21L
#define HAL_ERR_ERROR_COUNT_MAX 22L
#define HAL_ERR_IS_STARTED 23L
#define HAL_ERR_IS_STOPPED 24L
#define HAL_ERR_DATA_LOST 26L
#define HAL_ERR_RECV_ERROR 27L
#define HAL_ERR_SEND_ERROR 28L
#define HAL_ERR_NOT_ENABLED 29L
#define HAL_ERR_NO_ACCESS 30L
#define HAL_ERR_TIMEOUT 31L
#define HAL_ERR_FILE_ACCESS 32L
#define HAL_ERR_CMD_FAILED 33L
#define HAL_ERR_FILE_IOCTL 34L
#define HAL_ERR_FILE_READ 35L
#define HAL_ERR_FILE_WRITE 36L
#define HAL_ERR_FILE_FORMAT 37L
#define HAL_ERR_FILE_IDENTIFY 38L

#endif /* _HAL_ERR_ */